server:
  port: 9090

spring:
  application:
    name: microservice-course
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9898/realms/micro-services/protocol/openid-connect/certs
          issuer-uri: http://localhost:9898/realms/micro-services
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cursos_bd
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  instance:
    hostname: microservice-eureka
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
